namespace texasIcons {
export function getCowboyHatFrames(): Image[] {
return [
images.createImage(`. . . . .
. . . . .
. . . . .
. . . . .
. . . . .`),
images.createImage(`. . . . .
. . . . .
. . . . .
# . . . .
. . . . .`),
images.createImage(`. . . . .
. . . . .
. . . . .
. # . . .
# . . . .`),
images.createImage(`. . . . .
. . . . .
. . . . .
. . # . .
# # . . .`),
images.createImage(`. . . . .
. . . . .
# . . . .
# . . # .
# # # . .`),
images.createImage(`. . . . .
# . . . .
. # . . .
. # . . #
. # # # .`),
images.createImage(`# . . . .
. # . . .
. . # . .
. . # . .
# # # # #`),
images.createImage(`. # . . .
# . # . .
. . . # .
. . . # .
# # # # #`),
images.createImage(`# . # . .
. # . # .
. . . . #
. . . . #
# # # # #`),
images.createImage(`. # . # .
# . # . #
. . . . .
. . . . .
# # # # #`),
images.createImage(`. . # . #
. # . # .
# . . . .
# . . . .
# # # # #`),
images.createImage(`. . . # .
. . # . #
. # . . .
. # . . .
# # # # #`),
images.createImage(`. . . . #
. . . # .
. . # . .
. . # . .
# # # # #`),
images.createImage(`. . . . .
. . . . #
. . . # .
# . . # .
. # # # #`),
images.createImage(`. . . . .
. . . . .
. . . . #
. # . . #
. . # # #`),
images.createImage(`. . . . .
. . . . .
. . . . .
. . # . .
. . . # #`),
images.createImage(`. . . . .
. . . . .
. . . . .
. . . # .
. . . . #`),
images.createImage(`. . . . .
. . . . .
. . . . .
. . . . #
. . . . .`),
images.createImage(`. . . . .
. . . . .
. . . . .
. . . . .
. . . . .`)
]    
}
}