namespace texasIcons {
export function getLonghornFrames(): Image[] {
return [
images.createImage(`. . . . .
. . . . .
. . . . .
. . . . .
. . . . .`),
images.createImage(`. # . . .
# . . . .
. . . . .
. . . . .
. . . . .`),
images.createImage(`. . # . .
# # . . .
. . . . .
. . . . .
. . . . .`),
images.createImage(`. . . # .
# # # . .
# . . . .
. . . . .
. . . . .`),
images.createImage(`. . . . #
. # # # .
# # . . .
# . . . .
. . . . .`),
images.createImage(`. . . . .
. . # # #
# # # . .
# # . . .
# . . . .`),
images.createImage(`. . . . .
. . . # #
# # # # .
# # # . .
. # . . .`),
images.createImage(`. . . . .
# . . . #
# # # # #
. # # # .
. . # . .`),
images.createImage(`. . . . .
# # . . .
. # # # #
. . # # #
. . . # .`),
images.createImage(`. . . . .
# # # . .
. . # # #
. . . # #
. . . . #`),
images.createImage(`# . . . .
. # # # .
. . . # #
. . . . #
. . . . .`),
images.createImage(`. # . . .
. . # # #
. . . . #
. . . . .
. . . . .`),
images.createImage(`. . # . .
. . . # #
. . . . .
. . . . .
. . . . .`),
images.createImage(`. . . # .
. . . . #
. . . . .
. . . . .
. . . . .`),
images.createImage(`. . . . #
. . . . .
. . . . .
. . . . .
. . . . .`),
images.createImage(`. . . . .
. . . . .
. . . . .
. . . . .
. . . . .`)
]
}
}